### ISSUE TITLE
MagicMirror crashes after update to 2.17.1

### ISSUE THREAD

**Issue by meaple** [thobach/MMM-MicrosoftToDo#64]
I'm not dev and not sure if this is caused by MMM-MicrosoftToDo or MM itself, but after update I'm getting error while starting MM( nothing gets loaded), when MMM-MicrosoftToDo module is disabled(in config.js)it loads OK. This is what I can see in PM2 logs 

0|MagicMirror  | [01.10.2021 18:20.55.428] [ERROR] App threw an error during load
0|MagicMirror  | [01.10.2021 18:20.55.436] [ERROR] Error: Cannot find module 'request'
0|MagicMirror  | Require stack:
0|MagicMirror  | - /home/pi/MagicMirror/modules/MMM-MicrosoftToDo/node_helper.js
0|MagicMirror  | - /home/pi/MagicMirror/js/app.js
0|MagicMirror  | - /home/pi/MagicMirror/js/electron.js
0|MagicMirror  | - /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
0|MagicMirror  | -
0|MagicMirror  |     at Module._resolveFilename (internal/modules/cjs/loader.js:887:15)
0|MagicMirror  |     at Function.n._resolveFilename (electron/js2c/browser_init.js:257:1128)
0|MagicMirror  |     at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/module-alias/index.js:49:29)
0|MagicMirror  |     at Module._load (internal/modules/cjs/loader.js:732:27)
0|MagicMirror  |     at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
0|MagicMirror  |     at Module.require (internal/modules/cjs/loader.js:959:19)
0|MagicMirror  |     at require (internal/modules/cjs/helpers.js:88:18)
0|MagicMirror  |     at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-MicrosoftToDo/node_helper.js:9:17)
0|MagicMirror  |     at Module._compile (internal/modules/cjs/loader.js:1078:30)
0|MagicMirror  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
0|MagicMirror  | [01.10.2021 18:20.55.442] [ERROR] Whoops! There was an uncaught exception...
0|MagicMirror  | [01.10.2021 18:20.55.469] [ERROR]
0|MagicMirror  | Error: Cannot find module 'request'
0|MagicMirror  | Require stack:
0|MagicMirror  | - /home/pi/MagicMirror/modules/MMM-MicrosoftToDo/node_helper.js
0|MagicMirror  | - /home/pi/MagicMirror/js/app.js
0|MagicMirror  | - /home/pi/MagicMirror/js/electron.js
0|MagicMirror  | - /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
0|MagicMirror  | -
0|MagicMirror  |     at Module._resolveFilename (internal/modules/cjs/loader.js:887:15)
0|MagicMirror  |     at Function.n._resolveFilename (electron/js2c/browser_init.js:257:1128)
0|MagicMirror  |     at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/module-alias/index.js:49:29)
0|MagicMirror  |     at Module._load (internal/modules/cjs/loader.js:732:27)
0|MagicMirror  |     at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
0|MagicMirror  |     at Module.require (internal/modules/cjs/loader.js:959:19)
0|MagicMirror  |     at require (internal/modules/cjs/helpers.js:88:18)
0|MagicMirror  |     at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-MicrosoftToDo/node_helper.js:9:17)
0|MagicMirror  |     at Module._compile (internal/modules/cjs/loader.js:1078:30)
0|MagicMirror  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10) {
0|MagicMirror  |   code: 'MODULE_NOT_FOUND',
0|MagicMirror  |   requireStack: [
0|MagicMirror  |     '/home/pi/MagicMirror/modules/MMM-MicrosoftToDo/node_helper.js',
0|MagicMirror  |     '/home/pi/MagicMirror/js/app.js',
0|MagicMirror  |     '/home/pi/MagicMirror/js/electron.js',
0|MagicMirror  |     '/home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js',
0|MagicMirror  |     undefined
0|MagicMirror  |   ]
0|MagicMirror  | }

**Comment by gorim10** [comment]
Got the same problem today, but not after update, but after first instalation.

**Comment by meaple** [comment]
I've restored 2.16 and it was fine, updated module was OK as well, once 2.17.1 was installed it started crashing and causing MM not to display at all(black screen. as temporary solution installed MMM-Todoist

**Comment by gorim10** [comment]
how did you downgrade version ?

**Comment by meaple** [comment]
I’ve used my old card snapshot which was running on 2.16, but apparently there is a way of installing any version of MM and then moving your files across

**Comment by gorim10** [comment]
and how to do that ?

**Comment by meaple** [comment]
I think tag this was mentioned somewhere on MM forum. I’m not by my pc to have look

**Comment by meaple** [comment]
had a problem with different package and running 'npm install request --save' in MagicMirror folder + MM restart helped. I'm not sure if this is right way of overcoming it but ...

**Comment by gorim10** [comment]
git it. installed one more time mm and then todo module. thx

**Comment by Andygoes** [comment]
@meaple's suggestion worked for me:
1. Navigate to MM install folder in terminal
2. run 'npm install request --save' to install the missing node.js module ("request")
3. run 'npm start run' to restart MM

**Comment by gorim10** [comment]
Importat is that you have to be owner of that list. It cant be shared for you.

**Comment by spyder007** [comment]
The `request` module has been officially deprecated, and MagicMirror seems to have moved to `node-fetch` to solve this.

PR #66 Addresses this issue:  I migrated the API calls from `request` to `fetch`, among some other changes.

**Comment by thobach** [comment]
Issue was resolved with migration to node-fetch, which was merged.
